// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhJwK83NhL7PUjywwAkU2P7Ra1kaT5nY',
    appId: '1:517440766086:web:bff9ec7ea85b5ce7b55107',
    messagingSenderId: '517440766086',
    projectId: 'fasum-app-14ea8',
    authDomain: 'fasum-app-14ea8.firebaseapp.com',
    storageBucket: 'fasum-app-14ea8.firebasestorage.app',
    measurementId: 'G-CGCKXJPENK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDumDp8BPWuWAS7V8xGnoWxtUrALM_Z6g',
    appId: '1:517440766086:android:d86a763a752de71eb55107',
    messagingSenderId: '517440766086',
    projectId: 'fasum-app-14ea8',
    storageBucket: 'fasum-app-14ea8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo1Sj_kDcQ_x_BIY1IJiqG6VajSH0AtMM',
    appId: '1:517440766086:ios:e6499264018a251cb55107',
    messagingSenderId: '517440766086',
    projectId: 'fasum-app-14ea8',
    storageBucket: 'fasum-app-14ea8.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo1Sj_kDcQ_x_BIY1IJiqG6VajSH0AtMM',
    appId: '1:517440766086:ios:e6499264018a251cb55107',
    messagingSenderId: '517440766086',
    projectId: 'fasum-app-14ea8',
    storageBucket: 'fasum-app-14ea8.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANhJwK83NhL7PUjywwAkU2P7Ra1kaT5nY',
    appId: '1:517440766086:web:27f53c2d98f2ccb7b55107',
    messagingSenderId: '517440766086',
    projectId: 'fasum-app-14ea8',
    authDomain: 'fasum-app-14ea8.firebaseapp.com',
    storageBucket: 'fasum-app-14ea8.firebasestorage.app',
    measurementId: 'G-HT0ZF8T35F',
  );

}